apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    app.kubernetes.io/name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    name: vault
    app.kubernetes.io/name: vault
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
    app.kubernetes.io/name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-testing
  labels:
    name: chaos-testing
    app.kubernetes.io/name: chaos-mesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    app.kubernetes.io/name: applications
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    app.kubernetes.io/name: ingress-nginx

